### ISSUE TITLE
Always opens top left

### ISSUE THREAD

**Issue by Rabtokia** [chrdavis/SmartRename#1]
Hi,

Nice tool, save me writing powershell renames.

Suggestion: The tool always opens top left, I have a large screen and if the file explorer is on the right have to keep moving over, nice if it opened near mouse position.

The tool also removes the highlight after a rename, if I want to apply a rename again to the same files I have to highlight again.

**Comment by chrdavis** [comment]
Thanks for the feedback!

**Comment by chrdavis** [comment]
Try the latest release which fixes this.

https://github.com/chrdavis/SmartRename/releases/tag/v1.0.1
