### ISSUE TITLE
AppHangB1

### ISSUE THREAD

**Issue by cmheia** [chrdavis/SmartRename#3]
# Problem
- `v1.0.1`: Nothing happen, filename **NOT** change.
- `v1.0.2`: Explorer hang after click `Rename` in Smart Rename.
```
描述:
  出现了一个问题，该问题导致了此程序停止与 Windows 进行交互。

问题签名:
  问题事件名称:	AppHangB1
  应用程序名:	explorer.exe
  应用程序版本:	6.1.7601.17514
  应用程序时间戳:	4ce7a144
  挂起签名:	1b87
  挂起类型:	4
  OS 版本:	6.1.7601.2.1.0.256.48
  区域设置 ID:	2052
  其他挂起签名 1:	1b870c100bb960a7b35cc9f72664d083
  其他挂起签名 2:	266d
  其他挂起签名 3:	266dc3555ea632f7275cf8228f8ccf2f
  其他挂起签名 4:	dc0e
  其他挂起签名 5:	dc0e1aaff567eb1b66e04659942a608d
  其他挂起签名 6:	da5f
  其他挂起签名 7:	da5f255ec33a56a7432bd7bd8e9554d2
```

# Environment
System: Windows 7 SP1 x64
Filename: `Cortex_M0_.pdf`
Search for: `Cortex_M`
Replace with: `Cortex-M`

**Comment by chrdavis** [comment]
I will need more info about the hang.  Can this be easily reproduced?  Does this happen on other machines?
