### ISSUE TITLE
Support for regex replace group

### ISSUE THREAD

**Issue by reimaginesoft** [chrdavis/SmartRename#5]
Hello,

great feature will be to add regular expressions groups: 

**File name**
Artist title - Song name - 2019.01.01.mp3
**Regex**
(.*)-(\d{4}.\d{2}.\d{2})(\.mp3)
**Replace**
$1$0$2
**Result**:
2019.01.01 Artist title - Song name,mp3

This allow to cleanup file names.

**Comment by Bacco** [comment]
Installed just now to use the Regex ability... Then discovered that I can't use $1 etc. It really changes everything.

**Comment by chrdavis** [comment]
Seems to work for me using the latest version.  I had to modify the regex search and replace strings slightly
**File name**
Artist title - Song name - 2019.01.01.mp3
**Regex**
(.*) - (\d{4}.\d{2}.\d{2})(.mp3)
**Replace**
$2 $1$3
**Result:**
2019.01.01 Artist title - Song name.mp3

![image](https://user-images.githubusercontent.com/6734176/88311229-7a422400-ccc5-11ea-982c-084e4dae00ac.png)
